---
apiVersion: v1
kind: Secret
metadata:
  name: customers-gitops-repo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: GETA_URL/customers-gitops.git
  username: rouser
  password: ropswd
