apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
        name: customers-promote-51
        labels:
          backstage.io/kubernetes-id: customers
spec:
        taskRunSpecs:
        - pipelineTaskName: verify-enterprise-contract
          taskServiceAccountName: job-runner
        params:
          - name: git-repo-url
            value: GIT_URL/customers.git
          - name: git-revision
            value: main
          - name: source-image
            value: QUAY_HOST/quayadmin/customers
          - name: destination-image
            value: QUAY_HOST/quayadmin/customers
          - name: source-image-tag
            value: latest
          - name: destination-image-tag
            value: v1
          - name: namespace
            value: customers-user1
          - name: git-host
            value: GIT_HOST(without https)
          - name: git-owner
            value: ""
          - name: component-id
            value: customers
          - name: common-password-secret
            value: common-password-secret
          - name: argocd-host
            value: ARGOCD_HOST
          - name: policy-configuration
            value: 'git::github.com/redhat-gpe/config//default'
          - name: rekor-host
            value: http://rekor-server.trusted-artifact-signer.svc
          - name: tuf_mirror
            value: http://tuf.trusted-artifact-signer.svc
        pipelineRef:
          name: customers-promote
        serviceAccountName: image-pusher
        timeout: 1h0m0s
        workspaces:
          - name: images-url
            emptyDir: {} 
