kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-ns-rolebinding
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
